def getShipmentsToday(cursor):
	cursor.execute("SELECT Estim.DrawingFileName, DelTicket.DelTicketNo, CASE WHEN Releases.DelType=0 THEN 'Customer' WHEN Releases.Deltype=1 THEN 'Stock' ELSE 'Cancelled' END AS DelType, Delticket.CustCode, Releases.JobNo, DelTicket.CustPONum, Releases.PartNo, Releases.Qty, Billing.InvoiceTotal AS InvoiceTotal, DelTicket.ShipVia, convert(date, Releases.DueDate) AS DueDate, convert(date, DelTicket.Shipdate) AS ShipDate, Releases.Comments FROM DelTicket JOIN Releases ON DelTicket.DelTicketNo=Releases.DeliveryTicketNo LEFT JOIN Billing ON Billing.DelTicketNo=DelTicket.DelTicketNo LEFT JOIN Estim ON Releases.PartNo=Estim.PartNo WHERE DelTicket.ShipDate = convert(date, GETDATE())")
	return cursor.fetchall()

def getShipmentsPastWeek(cursor):
	cursor.execute("SELECT Estim.DrawingFileName, DelTicket.DelTicketNo, CASE WHEN Releases.DelType=0 THEN 'Customer' WHEN Releases.Deltype=1 THEN 'Stock' ELSE 'Cancelled' END AS DelType, Delticket.CustCode, Releases.JobNo, DelTicket.CustPONum, Releases.PartNo, Releases.Qty, Billing.InvoiceTotal AS InvoiceTotal, DelTicket.ShipVia, convert(date, Releases.DueDate) AS DueDate, convert(date, DelTicket.Shipdate) AS ShipDate, Releases.Comments FROM DelTicket JOIN Releases ON DelTicket.DelTicketNo=Releases.DeliveryTicketNo LEFT JOIN Billing ON Billing.DelTicketNo=DelTicket.DelTicketNo LEFT JOIN Estim ON Releases.PartNo=Estim.PartNo WHERE DelTicket.ShipDate >= DATEADD(week, -1, convert(date, GETDATE()))")
	return cursor.fetchall()

def getShipmentsReadyToShip(cursor):
	cursor.execute("SELECT Estim.DrawingFileName, convert(date, OrderDet.DueDate) AS DueDate, Orders.CustCode, OrderDet.JobNo, OrderDet.PartNo, OrderDet.QtyOrdered, OrderDet.QtyToStock, OrderDet.QtyShipped2Cust, OrderDet.QtyShipped2Stock, OrderDet.QtyCanceled, OrderDet.QtyToMake, ISNULL(BinLocations.QtyOnHand, 0) AS QtyOnHand FROM OrderDet LEFT JOIN BinLocations ON OrderDet.PartNo=BinLocations.PartNo JOIN Orders ON OrderDet.OrderNo=Orders.OrderNo LEFT JOIN Estim ON OrderDet.PartNo=Estim.PartNo WHERE OrderDet.Status='Open' AND NOT EXISTS(SELECT TOP 1 1 FROM OrderRouting WHERE OrderRouting.JobNo=OrderDet.JobNo AND OrderRouting.Status!='Closed' AND OrderRouting.Status!='Finished') AND (OrderDet.QtyOrdered + OrderDet.QtyToStock - OrderDet.QtyShipped2Cust - OrderDet.QtyShipped2Stock - OrderDet.QtyCanceled) <= (OrderDet.QtyToMake + ISNULL(BinLocations.QtyOnHand,0)) AND OrderDet.QtyOrdered>0 ORDER BY OrderDet.JobNo")
	return cursor.fetchall()